//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechTast_Management
{
    using System;
    
    public enum ActivityStatus : int
    {
        Pending = 1,
        QA = 2,
        Archive = 3
    }
}
