//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechTast_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int ActivityID { get; set; }
        public int Priority { get; set; }
        public string SerialNumber { get; set; }
        public System.DateTime DateReceived { get; set; }
        public int Age { get; set; }
        public int CurrentStatus { get; set; }
        public int TechnicianTechID { get; set; }
        public int UnitTypeTypeID { get; set; }
    
        public virtual Technician Technician { get; set; }
        public virtual UnitType UnitType { get; set; }
    }
}
